In [30]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import accuracy_score

In [31]:
df=pd.read_csv('ushape.csv')

In [32]:
df.columns = ['X1', 'X2', 'Y']

In [33]:
df

          X1        X2    Y
0   2.115098 -0.046244  1.0
1   0.882490 -0.075756  0.0
2  -0.055144 -0.037332  1.0
3   0.829545 -0.539321  1.0
4   2.112857  0.662084  1.0
..       ...       ...  ...
94  1.699453  0.587720  1.0
95  0.218623 -0.652521  1.0
96  0.952914 -0.419766  1.0
97 -1.318500  0.423112  0.0
98 -1.296818  0.184147  0.0

[99 rows x 3 columns]

In [38]:
X=df.iloc[:,0:2]
y=df.iloc[:,-1]

In [39]:
X

          X1        X2
0   2.115098 -0.046244
1   0.882490 -0.075756
2  -0.055144 -0.037332
3   0.829545 -0.539321
4   2.112857  0.662084
..       ...       ...
94  1.699453  0.587720
95  0.218623 -0.652521
96  0.952914 -0.419766
97 -1.318500  0.423112
98 -1.296818  0.184147

[99 rows x 2 columns]

In [40]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [41]:
x_train

          X1        X2
35  0.124124  1.000629
11  1.500096 -0.746364
83 -0.928582 -0.456320
44  0.931313  1.385178
96  0.952914 -0.419766
..       ...       ...
43  1.026588  0.377825
22  0.705157 -0.458924
72  2.022971  0.123251
15  0.301245  1.233157
40  0.641740 -0.393695

[79 rows x 2 columns]

In [42]:
lr=LogisticRegression()

In [43]:
lr.fit(x_train,y_train)

LogisticRegression()

In [44]:
y_pred=lr.predict(x_test)

In [45]:
accuracy_score(y_test,y_pred)

0.95

In [68]:
poly=PolynomialFeatures(degree=2)

In [69]:
x_train_new=poly.fit_transform(x_train)
x_test_new=poly.transform(x_test)

In [70]:
lr.fit(x_train_new,y_train)
y_pred1=lr.predict(x_test_new)

In [71]:
accuracy_score(y_test,y_pred1)

1.0

In [72]:
def plot_decision_boundary(X,y,degree=1):
    
    poly = PolynomialFeatures(degree=degree)
    X_trf = poly.fit_transform(X)
    
    clf = LogisticRegression()
    clf.fit(X_trf,y)
    
    accuracy = np.mean(cross_val_score(clf,X_trf,y,scoring='accuracy',cv=10))
    
    a=np.arange(start=X[:,0].min()-1, stop=X[:,0].max()+1, step=0.01)
    b=np.arange(start=X[:,1].min()-1, stop=X[:,1].max()+1, step=0.01)


    XX,YY=np.meshgrid(a,b)
    
    input_array=np.array([XX.ravel(),YY.ravel()]).T

    labels=clf.predict(poly.transform(input_array))
    
    plt.contourf(XX,YY,labels.reshape(XX.shape),alpha=0.5)
    plt.scatter(X[:,0],X[:,1], c=y)
    plt.title('Degree = {}, accuracy is {}'.format(degree,np.round(accuracy,4)))

In [73]:
plot_decision_boundary(X,y)

NameError: name 'cross_val_score' is not defined